version: '3.8'

services:
  ma3refa-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped